export const SERVICES = {
  ar: [
    {
      id: "income",
      icon: "building",
      title: "شراء عقارات مدرّة للدخل",
      lead: "عمائر سكنية، شقق، أدوار، ومحلات — هدفها دخل شهري منتظم.",
      who: "لمن يريد دخلًا ثابتًا ويفضّل الأصل الملموس على الأسهم والودائع.",
      inc: ["تحليل الدخل الفعلي من عقود إيجار الموثقة وسجل التحصيل", "تقدير الشواغر والصيانة والمصاريف التشغيلية بواقعية", "حساب العائد الصافي والعائد على الكاش مع التمويل وبدونه", "فحص فني للمبنى قبل التوصية"],
    },
    {
      id: "land",
      icon: "land",
      title: "أراضٍ للاستثمار والتطوير",
      lead: "للاحتفاظ طويل المدى أو للبناء والبيع.",
      who: "لمن يملك أفقًا زمنيًا طويلًا أو يفكر في تطوير صغير.",
      inc: ["التحقق من اعتماد المخطط والاستخدام ونظام البناء", "تحليل عرض الشوارع والواجهات وأثرها على القيمة", "مقارنة بصفقات أراضٍ مسجّلة قريبة", "دراسة مبسطة لجدوى التطوير عند الحاجة"],
    },
    {
      id: "growth",
      icon: "key",
      title: "فلل ووحدات بهدف النمو",
      lead: "عقارات في أحياء بطلب مستمر، للتأجير أو إعادة البيع أو السكن كاستثمار.",
      who: "لمن يريد أصلًا يحفظ القيمة وينمو مع المدينة.",
      inc: ["اختيار الحي والموقع داخله حسب الطلب المستقبلي", "تقييم جودة البناء والمطوّر والضمانات", "تقدير سيناريوهات إعادة البيع والتأجير", "تفاوض على السعر وشروط الدفع"],
    },
    {
      id: "offplan",
      icon: "doc",
      title: "مشاريع البيع على الخارطة",
      lead: "دخول مبكر بسعر أقل — مع مخاطر يجب فهمها.",
      who: "لمن يقبل الانتظار مقابل سعر دخول أقل وخطة دفع مرنة.",
      inc: ["التحقق من ترخيص المشروع لدى الجهات المختصة (وافي)", "مراجعة سجل المطوّر ومشاريعه المسلّمة", "قراءة العقد وجدول الدفعات وشروط التأخير", "مقارنة السعر النهائي بالوحدات الجاهزة المماثلة"],
    },
    {
      id: "offmarket",
      icon: "search",
      title: "الوصول لصفقات خارج المنصات",
      lead: "كثير من أفضل الصفقات لا تصل للإعلانات العامة.",
      who: "للمستثمر الجاهز الذي يستطيع اتخاذ القرار بسرعة.",
      inc: ["بحث نشط عبر شبكة الملاك والوسطاء والمطورين", "تنبيهك فور ظهور فرصة تطابق معاييرك", "تحليل سريع خلال ٤٨ ساعة لاتخاذ القرار", "حماية سرية بياناتك وميزانيتك في التفاوض"],
    },
    {
      id: "portfolio",
      icon: "chart",
      title: "مراجعة المحفظة العقارية",
      lead: "لديك عقارات؟ هل تعمل لصالحك فعلًا؟",
      who: "لمن يملك عقارًا أو أكثر ويريد رأيًا مستقلًا بالأرقام.",
      inc: ["حساب العائد الفعلي لكل عقار مقابل قيمته السوقية الحالية", "تحديد العقارات الضعيفة الأداء", "توصية: احتفظ، حسّن، أو بِع وأعد التوزيع", "خطة تنفيذ لإعادة التوزيع إن لزم"],
    },
  ],
  en: [
    { id: "income", icon: "building", title: "Income-producing property", lead: "Residential buildings, apartments, floors and retail — built for steady monthly income.", who: "For investors who want stable income and prefer tangible assets.", inc: ["Real income analysis from registered leases and collection history", "Realistic vacancy, maintenance and operating cost estimates", "Net yield and cash-on-cash, with and without financing", "Technical inspection before any recommendation"] },
    { id: "land", icon: "land", title: "Land for holding or development", lead: "Long-term holds or build-and-sell.", who: "For investors with a long horizon or considering small development.", inc: ["Plan approval, permitted use and building code checks", "Street width and frontage analysis and their effect on value", "Comparison with nearby registered land transactions", "Simple development feasibility when needed"] },
    { id: "growth", icon: "key", title: "Villas & units for growth", lead: "Property in districts with sustained demand — to rent, resell or live in as an investment.", who: "For investors seeking an asset that holds value and grows with the city.", inc: ["District and in-district location selection by future demand", "Build quality, developer and warranty assessment", "Resale and rental scenario estimates", "Price and payment-term negotiation"] },
    { id: "offplan", icon: "doc", title: "Off-plan projects", lead: "Early entry at a lower price — with risks you should understand.", who: "For investors who accept waiting in exchange for a lower entry price and flexible payments.", inc: ["Project licensing checks (Wafi)", "Developer track record review", "Contract, payment schedule and delay-clause review", "Final-price comparison with similar ready units"] },
    { id: "offmarket", icon: "search", title: "Off-market access", lead: "Many of the best deals never reach public listings.", who: "For ready investors who can decide quickly.", inc: ["Active search across owners, brokers and developers", "Alerts the moment a match appears", "Rapid analysis within 48 hours", "Confidentiality of your budget in negotiations"] },
    { id: "portfolio", icon: "chart", title: "Portfolio review", lead: "Already own property? Is it actually working for you?", who: "For owners of one or more properties who want an independent, numbers-based view.", inc: ["Actual return per property vs. current market value", "Identify under-performers", "Recommendation: hold, improve, or sell and redeploy", "Execution plan for redeployment if needed"] },
  ],
};
